"use client";
import { useEffect,useState,type FormEvent } from "react";
import { authenticatedRequest } from "@/features/auth/session";
import type { Company } from "@/features/companies/selection-state";
import { lineTotals,journalStatus,type EditableLine } from "./journal-model";
type Account={id:string;account_code:string;account_name:string;posting_allowed:boolean;status:string};
type Period={id:string;start_date:string;end_date:string;status:string};
export type Journal={id:string;entry_date:string;description:string;status:string;version:number;journal_no:string|null;approval_id:string|null;created_by:string;accounting_period_id:string;source_transaction_id:string|null;lines:EditableLine[];total_debit:string;total_credit:string;difference:string};
const blank=():EditableLine=>({account_id:"",debit_amount:"0",credit_amount:"0",memo:""});
export function JournalWorkspace({company}:{company:Company}) {
 const [rows,setRows]=useState<Journal[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[periods,setPeriods]=useState<Period[]>([]),[lines,setLines]=useState<EditableLine[]>([blank(),blank()]),[selected,setSelected]=useState<Journal|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true);
 const [from,setFrom]=useState("2025-01-01"),[to,setTo]=useState("2025-12-31");
 const headers={"X-Company-ID":company.id};
 useEffect(()=>{let active=true;if(!company.permissions.includes("journal.read"))return;const get=<T,>(path:string)=>authenticatedRequest<T>(path,{headers:{"X-Company-ID":company.id}});
 Promise.all([get<Journal[]>(`/journals?date_from=${from}&date_to=${to}`),get<Account[]>("/accounts"),get<Period[]>("/accounting/periods")]).then(([j,a,p])=>{if(active){setRows(j);setAccounts(a.filter(a=>a.posting_allowed&&a.status==="ACTIVE"));setPeriods(p)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[company.id,company.permissions,from,to,revision]);
 let total;try{total=lineTotals(lines)}catch{total=null}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{const date=String(f.get("date")),period=periods.find(p=>p.start_date<=date&&p.end_date>=date&&p.status==="OPEN");if(!period)throw new Error("해당 날짜의 열린 회계기간이 없습니다.");const row=await authenticatedRequest<Journal>("/journals",{method:"POST",headers,body:JSON.stringify({accounting_period_id:period.id,entry_date:date,description:f.get("description"),source_type:f.get("source")?"TRANSACTION":"MANUAL",source_transaction_id:f.get("source")||null,evidence_ids:[],lines})});setSelected(row);setRevision(r=>r+1)}catch(e){setError(e instanceof Error?e.message:"전표를 저장하지 못했습니다.")}finally{setBusy(false)}}
 async function command(action:string){if(!selected)return;setBusy(true);setError("");try{const row=await authenticatedRequest<Journal>(`/journals/${selected.id}/${action}`,{method:"POST",headers:{...headers,"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({expected_version:selected.version,approval_id:selected.approval_id,reason:"화면에서 전표를 검토했습니다.",reversal_date:from})});setSelected(row);setRevision(r=>r+1)}catch(e){setError(e instanceof Error?e.message:"전표 처리를 완료하지 못했습니다. 최신 내용을 다시 확인해 주세요.")}finally{setBusy(false)}}
 if(!company.permissions.includes("journal.read"))return null;
 return <section className="panel"><h2>회계 전표</h2><label>조회 시작일<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>조회 종료일<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{loading&&<p role="status">전표를 불러오고 있습니다…</p>}{error&&<p role="alert">{error}</p>}
 {company.permissions.includes("journal.propose")&&<form onSubmit={save}><h3>전표 작성</h3><label>전표일<input name="date" type="date" required defaultValue={from}/></label><label>적요<input name="description" required/></label><label>연결할 거래 식별자 (선택)<input name="source"/></label>
 {lines.map((l,i)=><div key={i}><label>계정 {i+1}<select value={l.account_id} onChange={e=>setLines(ls=>ls.map((r,n)=>n===i?{...r,account_id:e.target.value}:r))}><option value="">계정 선택</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.account_code} {a.account_name}</option>)}</select></label>{(["debit_amount","credit_amount"] as const).map(k=><label key={k}>{k==="debit_amount"?"차변":"대변"}<input inputMode="decimal" value={l[k]} onChange={e=>setLines(ls=>ls.map((r,n)=>n===i?{...r,[k]:e.target.value}:r))}/></label>)}<button type="button" onClick={()=>setLines(ls=>ls.filter((_,n)=>n!==i))}>분개 삭제</button></div>)}<button type="button" onClick={()=>setLines(ls=>[...ls,blank()])}>분개 추가</button><p aria-live="polite">차변 {total?.debit??"입력 확인"} · 대변 {total?.credit??"입력 확인"} · 차액 {total?.difference??"입력 확인"}</p><button disabled={busy||!total?.valid}>전표 초안 저장</button></form>}
 {rows.length===0&&!loading?<p>조회 기간의 전표가 없습니다.</p>:<ul>{rows.map(j=><li key={j.id}><button onClick={()=>setSelected(j)}>{j.entry_date} {j.journal_no??"번호 미부여"} · {j.description} · {journalStatus[j.status]??"상태 확인 필요"}</button></li>)}</ul>}
 {selected&&<article><h3>전표 상세</h3><p>{selected.description} · {journalStatus[selected.status]}</p><p>차변 {selected.total_debit} · 대변 {selected.total_credit} · 차액 {selected.difference}</p><table><thead><tr><th>계정</th><th>차변</th><th>대변</th></tr></thead><tbody>{selected.lines.map((l,i)=><tr key={i}><td>{accounts.find(a=>a.id===l.account_id)?.account_name??"계정 확인"}</td><td>{l.debit_amount}</td><td>{l.credit_amount}</td></tr>)}</tbody></table>{[["submit","제출","DRAFT","journal.submit"],["request-review","승인 요청","PROPOSED","journal.submit"],["approve","승인","REVIEW_REQUIRED","journal.approve"],["reject","반려","REVIEW_REQUIRED","journal.approve"],["post","장부 반영","APPROVED","journal.post"],["reverse","역분개 작성","POSTED","journal.reverse"]].map(([action,label,state,permission])=>selected.status===state&&company.permissions.includes(permission)&&<button key={action} disabled={busy} onClick={()=>command(action)}>{label}</button>)}<button onClick={()=>{setSelected(null);setRevision(r=>r+1)}}>최신 목록 다시 확인</button></article>}</section>;
}
