import builtins
from typing import Protocol
from uuid import UUID

from app.accounting.accounts.domain.entities import Account
from app.accounting.periods.domain.entities import Period
from app.accounting.settings.domain.entities import AccountingSettings
from app.accounting.templates.domain.entities import Template, TemplateAccount
from app.companies.application.contracts import CompanyUnitOfWork
from app.master_data.counterparties.application.contracts import Counterparties
from app.master_data.payment_terms.application.contracts import PaymentTerms


class SettingsRepository(Protocol):
    def get(self, company_id: UUID) -> AccountingSettings | None: ...
    def add(self, value: AccountingSettings) -> None: ...
    def update(self, value: AccountingSettings, expected_version: int) -> bool: ...


class Accounts(Protocol):
    def get(self, *, company_id: UUID, resource_id: UUID) -> Account | None: ...
    def list(self, company_id: UUID) -> builtins.list[Account]: ...
    def add(self, value: Account) -> None: ...


class Periods(Protocol):
    def get(self, *, company_id: UUID, resource_id: UUID) -> Period | None: ...
    def list(self, company_id: UUID) -> builtins.list[Period]: ...
    def add(self, value: Period) -> None: ...


class Templates(Protocol):
    def list(self) -> builtins.list[Template]: ...
    def accounts(self, template_id: UUID) -> builtins.list[TemplateAccount]: ...


class Sequences(Protocol):
    def ensure(self, company_id: UUID, fiscal_year: int, sequence_key: str) -> None: ...
    def allocate(self, company_id: UUID, fiscal_year: int, sequence_key: str) -> int: ...


class MasterUnitOfWork(CompanyUnitOfWork, Protocol):
    @property
    def payment_terms(self) -> PaymentTerms: ...
    @property
    def counterparties(self) -> Counterparties: ...
    @property
    def settings(self) -> SettingsRepository: ...
    @property
    def accounts(self) -> Accounts: ...
    @property
    def periods(self) -> Periods: ...
    @property
    def templates(self) -> Templates: ...
    @property
    def sequences(self) -> Sequences: ...
