from datetime import date
from typing import Protocol
from uuid import UUID

from app.accounting.application.contracts import MasterUnitOfWork
from app.accounting.transactions.domain.entities import Transaction


class Transactions(Protocol):
    def get(
        self, company_id: UUID, resource_id: UUID, *, lock: bool = False
    ) -> Transaction | None: ...
    def source(self, company_id: UUID, system: str, source_id: str) -> Transaction | None: ...
    def list(self, company_id: UUID, date_from: date, date_to: date) -> list[Transaction]: ...
    def add(self, value: Transaction) -> None: ...
    def update(self, value: Transaction, expected_version: int) -> bool: ...


class TransactionUnitOfWork(MasterUnitOfWork, Protocol):
    @property
    def transactions(self) -> Transactions: ...
    def has_journal(self, company_id: UUID, transaction_id: UUID) -> bool: ...
    def reference_exists(self, company_id: UUID, kind: str, resource_id: UUID) -> bool: ...
