from datetime import date
from typing import Protocol
from uuid import UUID

from app.accounting.journals.domain.entities import Journal
from app.accounting.transactions.application.contracts import TransactionUnitOfWork


class Journals(Protocol):
    def get(self, company_id: UUID, resource_id: UUID, *, lock: bool = False) -> Journal | None: ...
    def list(self, company_id: UUID, date_from: date, date_to: date) -> list[Journal]: ...
    def add(self, value: Journal) -> None: ...
    def update(
        self, value: Journal, expected_version: int, *, replace_lines: bool = False
    ) -> bool: ...
    def reversal(self, company_id: UUID, original: UUID) -> Journal | None: ...


class JournalUnitOfWork(TransactionUnitOfWork, Protocol):
    @property
    def journals(self) -> Journals: ...
    def lock_period(self, company_id: UUID, period_id: UUID) -> None: ...
    def lock_accounts(self, company_id: UUID, account_ids: tuple[UUID, ...]) -> None: ...
