import builtins
from typing import Protocol
from uuid import UUID

from app.master_data.counterparties.domain.children import Address, BankReference, Contact, Role
from app.master_data.counterparties.domain.entities import Counterparty


class Counterparties(Protocol):
    def get(self, *, company_id: UUID, resource_id: UUID) -> Counterparty | None: ...
    def list(
        self,
        company_id: UUID,
        *,
        name: str | None = None,
        status: str | None = None,
        role: str | None = None,
    ) -> builtins.list[Counterparty]: ...
    def add(self, value: Counterparty) -> None: ...
    def update(self, value: Counterparty, expected_version: int) -> bool: ...
    def add_role(self, company_id: UUID, value: Role) -> None: ...
    def add_contact(self, company_id: UUID, value: Contact) -> None: ...
    def add_address(self, company_id: UUID, value: Address) -> None: ...
    def add_bank(self, company_id: UUID, value: BankReference) -> None: ...
    def roles(self, company_id: UUID, resource_id: UUID) -> builtins.list[Role]: ...
    def contacts(self, company_id: UUID, resource_id: UUID) -> builtins.list[Contact]: ...
    def addresses(self, company_id: UUID, resource_id: UUID) -> builtins.list[Address]: ...
    def banks(self, company_id: UUID, resource_id: UUID) -> builtins.list[BankReference]: ...
    def match(
        self, company_id: UUID, business_number: str | None, legal_name: str
    ) -> builtins.list[Counterparty]: ...
