from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.companies.domain.entities import Company, CompanyAccess
from app.identity.auth.application.contracts import IdentityUnitOfWork


class Companies(Protocol):
    def accessible(
        self, user_id: UUID, company_id: UUID, *, lock: bool = False
    ) -> CompanyAccess | None: ...
    def list_accessible(self, user_id: UUID) -> list[CompanyAccess]: ...
    def create_tenant(self, tenant_id: UUID, name: str) -> None: ...
    def add(self, company: Company) -> None: ...
    def update(self, company: Company, expected_version: int) -> bool: ...
    def membership_status(self, company_id: UUID, user_id: UUID) -> str | None: ...
    def add_member(
        self, company_id: UUID, user_id: UUID, role_code: str, now: datetime
    ) -> None: ...


class CompanyUnitOfWork(IdentityUnitOfWork, Protocol):
    @property
    def companies(self) -> Companies: ...
