"""v0.2.3 권한 행렬을 명시적 permission 묶음으로 고정합니다. 미지정 권한은 거부합니다."""

ROLES = {
    "OWNER": "소유자",
    "ADMIN": "관리자",
    "ACCOUNTANT": "회계 담당자",
    "REVIEWER": "회계 검토자",
    "TAX_ACCOUNTANT": "세무 담당자",
    "TAX_REVIEWER": "세무 검토자",
    "VIEWER": "조회자",
    "AUDITOR": "감사자",
}

PERMISSION_GRANTS: dict[str, tuple[str, ...]] = {
    "company.read": tuple(ROLES),
    "counterparty.read": ("OWNER", "ADMIN", "ACCOUNTANT", "REVIEWER", "VIEWER", "AUDITOR"),
    "counterparty.create": ("OWNER", "ADMIN", "ACCOUNTANT"),
    "counterparty.update": ("OWNER", "ADMIN", "ACCOUNTANT"),
    "counterparty.merge": (),
    "company.update": ("OWNER", "ADMIN"),
    "company.members.manage": ("OWNER", "ADMIN"),
    "company.accounting_settings.update": ("OWNER", "ADMIN"),
    "company.tax_profile.update": ("OWNER", "ADMIN", "TAX_ACCOUNTANT"),
    "company.tax_profile.approve": ("OWNER", "TAX_REVIEWER"),
    "account.read": ("OWNER", "ADMIN", "ACCOUNTANT", "REVIEWER", "VIEWER", "AUDITOR"),
    "account.create": ("OWNER", "ADMIN", "ACCOUNTANT"),
    "account.update": ("OWNER", "ADMIN", "ACCOUNTANT"),
    "journal.read": ("OWNER", "ADMIN", "ACCOUNTANT", "REVIEWER", "VIEWER", "AUDITOR"),
    "journal.propose": ("ACCOUNTANT",),
    "journal.submit": ("ACCOUNTANT",),
    "journal.approve": ("REVIEWER", "OWNER"),
    "journal.post": ("REVIEWER", "OWNER"),
    "journal.reverse": ("REVIEWER", "OWNER"),
    "ledger.read": ("OWNER", "ADMIN", "ACCOUNTANT", "REVIEWER", "VIEWER", "AUDITOR"),
    "trial_balance.read": ("OWNER", "ADMIN", "ACCOUNTANT", "REVIEWER", "VIEWER", "AUDITOR"),
    "period.read": ("OWNER", "ADMIN", "ACCOUNTANT", "REVIEWER", "VIEWER", "AUDITOR"),
    "period.start_closing": ("ACCOUNTANT", "REVIEWER"),
    "period.close": ("REVIEWER", "OWNER"),
    "period.reopen.request": ("ACCOUNTANT", "REVIEWER"),
    "period.reopen.approve": ("OWNER",),
    "period.reopen.execute": ("OWNER",),
    "import.create": ("ACCOUNTANT", "TAX_ACCOUNTANT"),
    "import.preview": ("ACCOUNTANT", "TAX_ACCOUNTANT"),
    "import.confirm": ("ACCOUNTANT", "TAX_ACCOUNTANT"),
    "import.mapping.update": ("ACCOUNTANT", "TAX_ACCOUNTANT"),
    "evidence.upload": ("ACCOUNTANT", "TAX_ACCOUNTANT"),
    "evidence.read": (
        "OWNER",
        "ADMIN",
        "ACCOUNTANT",
        "REVIEWER",
        "TAX_ACCOUNTANT",
        "TAX_REVIEWER",
        "VIEWER",
        "AUDITOR",
    ),
    "evidence.download_raw": (),
    "receivable.read": ("ACCOUNTANT", "REVIEWER", "VIEWER"),
    "payable.read": ("ACCOUNTANT", "REVIEWER", "VIEWER"),
    "collection.record": ("ACCOUNTANT",),
    "payment.record": ("ACCOUNTANT",),
    "writeoff.request": ("ACCOUNTANT",),
    "writeoff.approve": ("REVIEWER", "OWNER"),
    "treasury.read": ("ACCOUNTANT", "REVIEWER", "OWNER"),
    "cash_adjustment.create": ("ACCOUNTANT",),
    "cash_adjustment.approve": ("REVIEWER", "OWNER"),
    "tax.read": ("TAX_ACCOUNTANT", "TAX_REVIEWER", "OWNER"),
    "tax.treatment.propose": ("TAX_ACCOUNTANT",),
    "tax.treatment.approve": ("TAX_REVIEWER",),
    "tax.adjustment.propose": ("TAX_ACCOUNTANT",),
    "tax.adjustment.approve": ("TAX_REVIEWER", "OWNER"),
    "tax.filing.calculate": ("TAX_ACCOUNTANT",),
    "tax.filing.approve": ("TAX_REVIEWER",),
    "tax.filing.ready": ("TAX_REVIEWER", "OWNER"),
    "audit.read": ("AUDITOR", "OWNER"),
}
