from enum import StrEnum


class EvidenceType(StrEnum):
    FILE = "FILE"
    IMAGE = "IMAGE"
    RECEIPT = "RECEIPT"
    TAX_INVOICE = "TAX_INVOICE"
    BANK_STATEMENT = "BANK_STATEMENT"
    CARD_STATEMENT = "CARD_STATEMENT"
    CONTRACT = "CONTRACT"
    EMAIL_REFERENCE = "EMAIL_REFERENCE"
    IMPORT_ROW = "IMPORT_ROW"
    SYSTEM_FACT = "SYSTEM_FACT"
    RULE_RESULT = "RULE_RESULT"
    HISTORICAL_JOURNAL = "HISTORICAL_JOURNAL"
